### ISSUE TITLE
Cannot create project

### ISSUE THREAD

**Issue by LuoTR** [WaveEngine/Feedback#85] opened 2021-07-02 06:30 UTC
Using WaveEngine 3.2.

```
[DEBUG] Starting build project: "F:\GameProjects\Rain\Rain.weproj"
[INFO] Starting build script '"Content\waveeditor.build.ps1"' with '"F:\GameProjects\Rain\Rain.Windows.sln"' for the project '"Rain.Editor"'
[VERBOSE] Build script arguments: "-noprofile -executionPolicy \"RemoteSigned\" -File \"Content\waveeditor.build.ps1\" -slnPath \"F:\GameProjects\Rain\Rain.Windows.sln\" -projectName \"Rain.Editor\" -projectPath \"F:\GameProjects\Rain\Rain.Editor\Rain.Editor.csproj\" -outputFolder \"F:\GameProjects\Rain\.waveengine\Rain.Windows\Build\temp\gwbq3hei.e2u\bin\" -intermediateOutputFolder \"F:\GameProjects\Rain\.waveengine\Rain.Windows\Build\temp\gwbq3hei.e2u\obj\" -watchTargetPath \"C:\Users\expWi\.waveengine\WaveEngine.Editor\3.2.0.7787-preview\Editor\Content\waveeditor.watch.targets\" -watchOutputFilePath \"C:\Users\expWi\AppData\Local\Temp\jldwscuf.txq\" -executeNugetRestore \"False\" -verbosity \"minimal\" -culture \"en\""
[INFO]   正在确定要还原的项目…
[INFO]   所有项目均是最新的，无法还原。
[INFO] F:\GameProjects\Rain\Rain.Windows\Rain.Windows.csproj : error MSB4057: 该项目中不存在目标“Rain_Editor”。
[INFO] F:\GameProjects\Rain\Rain\Rain.csproj : error MSB4057: 该项目中不存在目标“Rain_Editor”。
[INFO] F:\GameProjects\Rain\Rain.Editor\Rain.Editor.csproj : error MSB4057: 该项目中不存在目标“Rain_Editor”。
[ERROR] Error building 'Rain.Editor' in 'F:\GameProjects\Rain\Rain.Windows.sln'.
[ERROR] The project has some errors that prevents it to be built, check the log and reload the project when they are fixed.
```

Tried to reload the project and create another project, not working.

**Comment by BChapoulie** [comment] 2021-07-09 08:35
Hello, 

I've ran into an issue like this that was solved by updating VisualStudio : https://github.com/WaveEngine/Feedback/issues/80

Hope this helps.

**Comment by minolo** [comment] 2021-07-14 11:54
Hello there!

Thanks for your help @BChapoulie! 

I'm going to close this issue for now because it seems that it's a duplicate of the linked issue. @LuoTR If the problem persists you can reopen it and we'll look into it.

**Closed by minolo** 2021-07-14 11:54 UTC
