### ISSUE TITLE
SharpDXException When Running any Template , sample

### ISSUE THREAD

**Issue by Shadow4walker** [WaveEngine/Feedback#41] opened 2020-12-07 14:27 UTC
I'm facing the same issue like others in the issues section
SharpDXException  occurred after creating  a new project or when trying any of the samples 
vs build the project without any error but when running the output file, some exception hit also the wave Editor itself can't open the project due to this

Exception Message 
> SharpDX.SharpDXException: 'HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

StackTrace

>    at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device5.CreateFence(Int64 initialValue, FenceFlags flags, Guid returnedInterface, Fence fenceOut)
   at SharpDX.Direct3D11.Fence..ctor(Device5 device, Int64 initialValue, FenceFlags flags)
   at WaveEngine.DirectX11.DX11CommandQueue..ctor(DX11GraphicsContext graphicsContext)
   at WaveEngine.DirectX11.DX11ResourceFactory.CreateCommandQueueInternal(CommandQueueType queueType)
   at WaveEngine.Common.Graphics.ResourceFactory.CreateCommandQueue(CommandQueueType queueType)
   at WaveEngine.Framework.Services.GraphicsPresenter.OnAttached()
   at WaveEngine.Framework.AttachableObject.Attach()
   at WaveEngine.Framework.Services.ServiceInterceptor.InitializeServices()
   at WaveEngine.Framework.Application.Initialize()
   at MyWaveProject.MyApplication.Initialize() in Test\MyWaveProject\MyWaveProject\MyApplication.cs:line 25
   at MyWaveProject.Windows.Program.<>c__DisplayClass0_0.<Main>b__0() in Test\MyWaveProject\MyWaveProject.Windows\Program.cs:line 31
   at WaveEngine.Forms.FormsWindowsSystem.CreateLoopThread(Action loadAction, Action renderCallback)
   at WaveEngine.Common.Graphics.WindowsSystem.Run(Action loadAction, Action renderCallback)
   at MyWaveProject.Windows.Program.Main(String[] args) in Test\MyWaveProject\MyWaveProject.Windows\Program.cs:line 30

**Comment by danielcaceresm** [comment] 2020-12-11 08:50
Duplicate of #38

**Closed** 2021-03-12 13:02 UTC
